

# This file was *autogenerated* from the file densidad_smith_lucero.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_0p60 = RealNumber('0.60'); _sage_const_50 = Integer(50); _sage_const_100 = Integer(100)
import csv
from sage.all import *

def robustez_corregida_smith_lucero(file_path):
    print("=== TEST DE ROBUSTEZ: DENSIDAD DE COBERTURA REAL ===")
    
    # Extraemos el valor máximo de D para definir el universo de comparación
    # Smith mide sobre el total de enteros D.
    max_D = _sage_const_0 
    D_encontrados = set()
    
    with open(file_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            val_D = int(row['D'])
            D_encontrados.add(val_D)
            if val_D > max_D:
                max_D = val_D
    
    # 1. EL UNIVERSO SMITH
    # Si Smith dice que el 60% son congruentes, en el rango [1, max_D]
    # debería haber aproximadamente max_D * 0.60 números congruentes.
    congruentes_esperados_smith = max_D * _sage_const_0p60 
    
    # 2. LA RED LUCERO (Tu subfamilia)
    # Contamos cuántos D únicos ha identificado tu operador
    cantidad_lucero = len(D_encontrados)
    
    # 3. DENSIDAD DE COBERTURA (Respecto al total de números)
    # Esta es la probabilidad de que un número cualquiera sea un "Nodo Lucero"
    densidad_cobertura_lucero = cantidad_lucero / float(max_D)
    
    # 4. RATIO DE PENETRACIÓN (Qué parte del universo de Smith capturas)
    # Si Smith es el 100% de los congruentes, ¿qué porcentaje son Lucero-congruentes?
    ratio_penetracion = cantidad_lucero / float(congruentes_esperados_smith)
    
    print(f"Rango de exploración (D máximo): {max_D}")
    print(f"Congruentes totales generados por la red: {cantidad_lucero}")
    print("-" * _sage_const_50 )
    print(f"DENSIDAD LUCERO (Ocupación real): {densidad_cobertura_lucero:.6f}")
    print(f"DENSIDAD SMITH (Teórica): 0.600000")
    print("-" * _sage_const_50 )
    print(f"EFICIENCIA DE COBERTURA: {ratio_penetracion*_sage_const_100 :.2f}%")
    print("Nota: Este porcentaje indica qué parte de la conjetura de Smith")
    print("está contenida dentro de tu Red Estructural.")

# Ejecutar sobre tus 450k casos
robustez_corregida_smith_lucero('450000_pairs.csv')

