

# This file was *autogenerated* from the file densidad_lucero.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_50 = Integer(50)
import csv
from sage.all import *

def test_rigor_densidad(file_path):
    print(f"Analizando coherencia de densidad Lucero (rho = 0.152)")
    
    j_list = []
    with open(file_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            j_list.append(int(row['j']))
    
    j_list = sorted(list(set(j_list))) # Solo j únicos
    distancias = [j_list[i+_sage_const_1 ] - j_list[i] for i in range(len(j_list)-_sage_const_1 )]
    
    # Estadísticos de la Veta
    media_dist = float(sum(distancias)) / len(distancias)
    varianza = float(sum((x - media_dist)**_sage_const_2  for x in distancias)) / len(distancias)
    
    print("-" * _sage_const_50 )
    print(f"Media de distancia entre nodos (Delta j): {media_dist:.4f}")
    print(f"Densidad Observada (1/media): {_sage_const_1 /media_dist:.4f}")
    print(f"Varianza de la estructura: {varianza:.4f}")
    
    # Interpretación
    if varianza < media_dist * _sage_const_2 :
        print("ESTADO: Red Altamente Estructurada (No aleatoria)")
    else:
        print("ESTADO: Distribución Dispersa")
    print("-" * _sage_const_50 )

# Ejecuta esto sobre tus 450k casos
test_rigor_densidad('450000_pairs.csv')

