

# This file was *autogenerated* from the file ec_structure.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_6 = Integer(6)# CÓDIGO MÍNIMO QUE FUNCIONA - COPIA DIRECTO
E = EllipticCurve([_sage_const_0 , -_sage_const_3 /_sage_const_2 , _sage_const_0 , _sage_const_1 /_sage_const_2 , _sage_const_1 /_sage_const_4 ])

print("=== RESULTADOS COMPLETOS ===")
print("Curva:", E)
print("Delta:", E.discriminant())
print("Torsión:", E.torsion_order())
print("Conductor:", E.conductor())
print("c4 =", E.c4())
print("c6 =", E.c6())
print("j =", E.j_invariant())

print("\nPUNTOS ANCLA:")
for n in [_sage_const_4 ,_sage_const_5 ,_sage_const_8 ]:
    m2 = _sage_const_4 *n**_sage_const_3  - _sage_const_6 *n**_sage_const_2  + _sage_const_2 *n + _sage_const_1 
    print("n =", n, "- m^2 =", m2, "- m =", int(sqrt(m2)))

print("\nRank (intento):")
print(E.rank())

