"""
CÁLCULO DIRECTO SOBRE LA CURVA ORIGINAL
Ecuación: m² = 4n³ - 6n² + 2n + 1
Forma Weierstrass para Sage: y² = x³ - (3/2)x² + (1/2)x + 1/4
Relación: n = x, m = 2y
"""


# This file was *autogenerated* from the file ec_structure_robust.sage
from sage.all_cmdline import *   # import sage library

_sage_const_60 = Integer(60); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_13 = Integer(13); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_19 = Integer(19); _sage_const_8 = Integer(8); _sage_const_21 = Integer(21); _sage_const_41 = Integer(41); _sage_const_65 = Integer(65); _sage_const_35 = Integer(35); _sage_const_6 = Integer(6)
print("="*_sage_const_60 )
print("ANÁLISIS DIRECTO DE LA CURVA ORIGINAL")
print("="*_sage_const_60 )

# -----------------------------------------------------------------
# 1. DEFINICIÓN DE LA CURVA
# -----------------------------------------------------------------
print("\n1. DEFINICIÓN DE LA CURVA")
print("   Ecuación original: m² = 4n³ - 6n² + 2n + 1")
print("   Forma Weierstrass: y² = x³ - (3/2)x² + (1/2)x + 1/4")
print("   Relación: n = x, m = 2y")

E = EllipticCurve([_sage_const_0 , -_sage_const_3 /_sage_const_2 , _sage_const_0 , _sage_const_1 /_sage_const_2 , _sage_const_1 /_sage_const_4 ])  # Curva original
print(f"   Curva en Sage: {E}")

# -----------------------------------------------------------------
# 2. INVARIANTES BÁSICOS
# -----------------------------------------------------------------
print("\n2. INVARIANTES BÁSICOS")
print(f"   Discriminante (Δ) = {E.discriminant()}")
print(f"   j-invariante = {E.j_invariant()}")
print(f"   Conductor = {E.conductor()}")
print(f"   c4 = {E.c4()}")
print(f"   c6 = {E.c6()}")

# -----------------------------------------------------------------
# 3. ESTRUCTURA DE TORSIÓN
# -----------------------------------------------------------------
print("\n3. ESTRUCTURA DE TORSIÓN")
torsion = E.torsion_subgroup()
print(f"   Orden del subgrupo de torsión = {torsion.order()}")
print(f"   Estructura del grupo = {torsion.invariants()}")

# -----------------------------------------------------------------
# 4. RANGO Y GENERADORES
# -----------------------------------------------------------------
print("\n4. RANGO (esto puede tardar unos segundos...)")
try:
    # Intentar cálculo del rango
    rank = E.rank()
    print(f"   Rango de la curva = {rank}")
    
    if rank > _sage_const_0 :
        print(f"\n   Buscando generadores...")
        gens = E.gens()
        print(f"   Número de generadores encontrados: {len(gens)}")
        
        for i, gen in enumerate(gens[:_sage_const_3 ]):  # Mostrar máximo 3
            x_gen, y_gen = gen.xy()
            print(f"   Generador G{i+_sage_const_1 }: ({x_gen}, {y_gen})")
            # Convertir a coordenadas (n, m) originales
            n_gen = x_gen
            m_gen = _sage_const_2 *y_gen
            print(f"     → En coordenadas originales: (n={n_gen}, m={m_gen})")
            
        if len(gens) > _sage_const_3 :
            print(f"   ... y {len(gens)-_sage_const_3 } generadores más")
except Exception as e:
    print(f"   Error calculando rango/generadores: {e}")
    print("   Usando método aproximado...")
    rank_bounds = E.rank_bounds()
    print(f"   Límites del rango: {rank_bounds}")

# -----------------------------------------------------------------
# 5. PUNTOS ANCLA (verificación directa)
# -----------------------------------------------------------------
print("\n5. VERIFICACIÓN DE PUNTOS ANCLA")

# Triples: (n, j, m=2j-1) del preprint
anchors = [
    {"n": _sage_const_4 , "j": _sage_const_7 , "m": _sage_const_13 },
    {"n": _sage_const_5 , "j": _sage_const_10 , "m": _sage_const_19 },
    {"n": _sage_const_8 , "j": _sage_const_21 , "m": _sage_const_41 }
]

print("   n |  j | m=2j-1 | ¿Punto en curva? | Coordenadas (x,y) en E")
print("   " + "-"*_sage_const_65 )

for a in anchors:
    n, m = a["n"], a["m"]
    # Convertir a coordenadas de E: x = n, y = m/2
    x, y = n, m/_sage_const_2 
    
    # Verificar si el punto está en E
    try:
        P = E(x, y)
        on_curve = "SÍ"
        # Verificar la ecuación explícitamente
        left = y**_sage_const_2 
        right = x**_sage_const_3  - (_sage_const_3 /_sage_const_2 )*x**_sage_const_2  + (_sage_const_1 /_sage_const_2 )*x + _sage_const_1 /_sage_const_4 
        verified = "✓" if left == right else "✗"
    except Exception:
        on_curve = "NO"
        verified = ""
    
    print(f"   {n:2} | {a['j']:2} | {m:6}  | {on_curve:^16} | ({x}, {y}) {verified}")

# -----------------------------------------------------------------
# 6. PUNTOS INTEGRALES (en coordenadas originales)
# -----------------------------------------------------------------
print("\n6. PUNTOS INTEGRALES EN COORDENADAS ORIGINALES (n, m)")
print("   Buscando puntos con n, m enteros...")

try:
    # Obtener puntos integrales en la curva de Weierstrass
    int_points_weier = E.integral_points()
    
    if int_points_weier:
        print(f"   Se encontraron {len(int_points_weier)} puntos integrales en E")
        print("\n   Puntos integrales (mostrando primeros 10):")
        print("   (x, y) en E | (n, m) originales")
        print("   " + "-"*_sage_const_35 )
        
        for i, P in enumerate(int_points_weier[:_sage_const_10 ]):
            x_val, y_val = P.xy()
            n_val = x_val
            m_val = _sage_const_2 *y_val
            print(f"   ({x_val}, {y_val}) | (n={n_val}, m={m_val})")
        
        if len(int_points_weier) > _sage_const_10 :
            print(f"   ... y {len(int_points_weier)-_sage_const_10 } puntos más")
    else:
        print("   No se encontraron puntos integrales en E")
        
except Exception as e:
    print(f"   Error buscando puntos integrales: {e}")

# -----------------------------------------------------------------
# 7. VERIFICACIÓN FINAL DE CONSISTENCIA
# -----------------------------------------------------------------
print("\n" + "="*_sage_const_60 )
print("VERIFICACIÓN FINAL DE CONSISTENCIA")
print("="*_sage_const_60 )

# Verificar que los puntos ancla satisfacen la ecuación original
print("\nVerificación algebraica directa:")
for a in anchors:
    n, m = a["n"], a["m"]
    left = m**_sage_const_2 
    right = _sage_const_4 *n**_sage_const_3  - _sage_const_6 *n**_sage_const_2  + _sage_const_2 *n + _sage_const_1 
    print(f"   n={n}, m={m}: m²={left}, 4n³-6n²+2n+1={right}, ¿Iguales? {left == right}")

# Información sobre la transformación
print(f"\nResumen de la curva original:")
print(f"   • j-invariante: {E.j_invariant()}")
print(f"   • Torsión: {torsion.invariants()}")
try:
    print(f"   • Rango: {rank}")
except:
    pass
print(f"   • Puntos ancla verificados: {len(anchors)}")
print("\n" + "="*_sage_const_60 )
print("ANÁLISIS COMPLETADO")
print("="*_sage_const_60 )

