

# This file was *autogenerated* from the file ec_visual.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_50 = Integer(50); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_0p5 = RealNumber('0.5'); _sage_const_20 = Integer(20); _sage_const_100 = Integer(100); _sage_const_0p1 = RealNumber('0.1'); _sage_const_120 = Integer(120); _sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_300 = Integer(300); _sage_const_7 = Integer(7)# y^2 = 4n^3 - 6n^2 + 2n + 1
# Modelo escalado para Sage: y^2 = x^3 - 6x^2 + 8x + 16
E = EllipticCurve([_sage_const_0 , -_sage_const_6 , _sage_const_0 , _sage_const_8 , _sage_const_16 ]) 

# --- SECCIÓN INSTRUCTIVA (SALIDA DE TERMINAL) ---
print("-" * _sage_const_50 )
print("ANÁLISIS TEÓRICO DE LA RED (NUCLEUS d=2)")
print("-" * _sage_const_50 )
print(f"Ecuación de Weierstrass: {E}")
print(f"Rango de Mordell-Weil (r): {E.rank()}")
print(f"Grupo de Torsión: {E.torsion_subgroup()}")

# Obtención de puntos integrales y mapeo a tu variable 'n'
puntos = E.integral_points()
print("\nIdentificación de Anchor Pairs (Nodos de la Red):")
for P in puntos:
    if P[_sage_const_1 ] > _sage_const_0 : # Solo mostramos la rama positiva para claridad
        n_actual = int(P[_sage_const_0 ]/_sage_const_2 )
        j_actual = int((P[_sage_const_1 ] + _sage_const_4 ) / _sage_const_8 ) # Inversión del escalado para recuperar tu 'j'
        print(f"Nodo detectado: n = {n_actual} | Punto en curva: {P[:_sage_const_2 ]}")

# --- SECCIÓN GRÁFICA (VISUALIZACIÓN OPTIMIZADA) ---
x_min, x_max = -_sage_const_0p5 , _sage_const_20 
y_min, y_max = -_sage_const_100 , _sage_const_100 

# aspect_ratio=0.1 estira el eje X para que la curva no sea una línea vertical
plot_curva = E.plot(xmin=x_min, xmax=x_max, ymin=y_min, ymax=y_max, 
                    color='blue', thickness=_sage_const_2 , gridlines=True, 
                    axes_labels=['$x (2n)$', '$y$'],
                    aspect_ratio=_sage_const_0p1 ) 

plot_puntos = Graphics()
for P in puntos:
    if x_min <= P[_sage_const_0 ] <= x_max:
        plot_puntos += point(P[:_sage_const_2 ], color='red', size=_sage_const_120 , zorder=_sage_const_3 )
        if P[_sage_const_1 ] > _sage_const_0 :
            plot_puntos += text(f"n={int(P[_sage_const_0 ]/_sage_const_2 )}", (P[_sage_const_0 ], P[_sage_const_1 ]+_sage_const_10 ), 
                                color='black', fontsize=_sage_const_12 , fontweight='bold')

grafico_final = plot_curva + plot_puntos
grafico_final.save("red_autorreferencial_ajustada.png", dpi=_sage_const_300 , figsize=[_sage_const_12 , _sage_const_7 ])

print("-" * _sage_const_50 )
print("Gráfica guardada como 'red_autorreferencial_ajustada.png'")
print("Visualización escalada para observar la curvatura y los puntos ancla.")

