

# This file was *autogenerated* from the file elliptic_curve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1001 = Integer(1001); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_13 = Integer(13); _sage_const_0 = Integer(0); _sage_const_10001 = Integer(10001); _sage_const_10 = Integer(10)# Código Sage para encontrar puntos enteros en la curva elíptica asociada a pares autoreferenciales
# La condición es: 1 + 2*n*(n-1)*(2*n-1) = m^2
# Esto define la curva: m^2 = 4*n^3 - 6*n^2 + 2*n + 1

# Enfoque 1: Búsqueda directa para verificar los pares
print("=== BÚSQUEDA DIRECTA (n hasta 1000) ===")
solutions = []
for n in range(_sage_const_2 , _sage_const_1001 ):
    D = n*(n-_sage_const_1 )*(_sage_const_2 *n-_sage_const_1 )
    disc = _sage_const_1  + _sage_const_2 *D
    m = int(sqrt(disc))
    if m*m == disc:
        j = (_sage_const_1  + m) // _sage_const_2 
        if _sage_const_2 *j*(j-_sage_const_1 ) == D:
            solutions.append((n, j, D))
            print(f"n={n}, j={j}, D={D}")

print(f"\nSe encontraron {len(solutions)} soluciones: {solutions}")

# Enfoque 2: Usando curvas elípticas en Sage
print("\n=== USANDO CURVAS ELÍPTICAS ===")
# Definimos el anillo de polinomios
R = QQ['x, y, z']; (x, y, z,) = R._first_ngens(3)
# Ecuación cúbica homogénea: y^2*z = 4*x^3 - 6*x^2*z + 2*x*z^2 + z^3
cubic = y**_sage_const_2 *z - (_sage_const_4 *x**_sage_const_3  - _sage_const_6 *x**_sage_const_2 *z + _sage_const_2 *x*z**_sage_const_2  + z**_sage_const_3 )

# Punto racional conocido (usamos n=4, m=13)
point = [_sage_const_4 , _sage_const_13 , _sage_const_1 ]

# Convertimos la cúbica a forma de Weierstrass
try:
    E = EllipticCurve_from_cubic(cubic, point, morphism=False)
    print(f"Curva elíptica en forma de Weierstrass: {E}")
    print(f"Ecuación: {E.ainvs()}")
    
    # Encontramos todos los puntos enteros en la curva elíptica
    integral_pts = E.integral_points()
    print(f"\nPuntos enteros en la curva elíptica: {integral_pts}")
    print(f"Número de puntos enteros: {len(integral_pts)}")
    
    # Mapeamos los puntos de vuelta a la cúbica original
    # Necesitamos el morfismo que mapea la cúbica a la curva elíptica
    phi = EllipticCurve_from_cubic(cubic, point, morphism=True)
    print("\nPuntos correspondientes en la cúbica original (n, m):")
    for P in integral_pts:
        # Mapeamos el punto de E a la cúbica
        preimage = phi.inverse()(P)
        # Normalizamos a coordenadas afines (z=1)
        if preimage[_sage_const_2 ] != _sage_const_0 :
            n_val = preimage[_sage_const_0 ]/preimage[_sage_const_2 ]
            m_val = preimage[_sage_const_1 ]/preimage[_sage_const_2 ]
            if n_val.is_integer() and m_val.is_integer():
                n_int = Integer(n_val)
                m_int = Integer(m_val)
                # Calculamos j
                j_val = (_sage_const_1  + m_int) // _sage_const_2 
                D_val = n_int*(n_int-_sage_const_1 )*(_sage_const_2 *n_int-_sage_const_1 )
                print(f"  n={n_int}, m={m_int}, j={j_val}, D={D_val}")
                
except Exception as e:
    print(f"Error: {e}")
    print("Intentando método alternativo...")
    
    # Método alternativo: usar la ecuación directamente con búsqueda
    print("\nBúsqueda extendida (n hasta 10^4):")
    extended_solutions = []
    for n in range(_sage_const_2 , _sage_const_10001 ):
        D = n*(n-_sage_const_1 )*(_sage_const_2 *n-_sage_const_1 )
        disc = _sage_const_1  + _sage_const_2 *D
        m = int(sqrt(disc))
        if m*m == disc:
            j = (_sage_const_1  + m) // _sage_const_2 
            if _sage_const_2 *j*(j-_sage_const_1 ) == D:
                extended_solutions.append((n, j, D))
    
    print(f"Soluciones encontradas con n ≤ 10^4: {len(extended_solutions)}")
    if len(extended_solutions) > _sage_const_0 :
        print("Primeras 10 soluciones:")
        for sol in extended_solutions[:_sage_const_10 ]:
            print(f"  n={sol[_sage_const_0 ]}, j={sol[_sage_const_1 ]}, D={sol[_sage_const_2 ]}")
    if len(extended_solutions) > _sage_const_10 :
        print(f"  ... y {len(extended_solutions)-_sage_const_10 } más")

