

# This file was *autogenerated* from the file generators.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_50 = Integer(50); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0p5 = RealNumber('0.5'); _sage_const_40 = Integer(40); _sage_const_150 = Integer(150); _sage_const_0p1 = RealNumber('0.1'); _sage_const_120 = Integer(120); _sage_const_3 = Integer(3); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10); _sage_const_300 = Integer(300); _sage_const_7 = Integer(7)# y^2 = 4n^3 - 6n^2 + 2n + 1
# Transformación rigurosa: X = 4n, Y = 4y
# Sustituyendo: (4y)^2 = 4(4n)^3/4 - 6(4n)^2/4 + 8(4n)/4 + 16? No.
# La forma entera correcta que usas es: Y^2 = X^3 - 6X^2 + 8X + 16
E = EllipticCurve([_sage_const_0 , -_sage_const_6 , _sage_const_0 , _sage_const_8 , _sage_const_16 ]) 

# --- SECCIÓN INSTRUCTIVA (SALIDA DE TERMINAL CORREGIDA) ---
print("-" * _sage_const_50 )
print("ANÁLISIS TEÓRICO: GENERADORES DE LA RED (BASE DE MORDELL-WEIL)")
print("-" * _sage_const_50 )
print(f"Ecuación escalada: {E}")
print(f"Rango: {E.rank()} | Torsión: {E.torsion_subgroup()}")

generadores = E.gens()
for i, G in enumerate(generadores):
    # Traducción basada en X = 4n -> n = X/4
    # Traducción basada en Y = 4y -> y = Y/4 -> 2j-1 = Y/4 -> j = (Y/4 + 1)/2 = (Y+4)/8
    n_gen = G[_sage_const_0 ]/_sage_const_4 
    j_gen = (G[_sage_const_1 ] + _sage_const_4 )/_sage_const_8 
    print(f"Generador P{i+_sage_const_1 }: {G[:_sage_const_2 ]}")
    print(f"  -> Interpretación: n = {n_gen}, j = {j_gen}")

# Verificación de suma de puntos
P1, P2 = generadores[_sage_const_0 ], generadores[_sage_const_1 ]
P_suma = P1 + P2
print("-" * _sage_const_50 )
print(f"Suma de Generadores (P1 + P2): {P_suma[:_sage_const_2 ]}")
print(f"  -> Nodo resultante: n = {P_suma[_sage_const_0 ]/_sage_const_4 }, j = {(P_suma[_sage_const_1 ]+_sage_const_4 )/_sage_const_8 }")
print("-" * _sage_const_50 )

# --- SECCIÓN GRÁFICA (MANTENIENDO TU CONFIGURACIÓN LOGRADA) ---
x_min, x_max = -_sage_const_0p5 , _sage_const_40  # Expandido ligeramente para ver más anclas
y_min, y_max = -_sage_const_150 , _sage_const_150 

plot_curva = E.plot(xmin=x_min, xmax=x_max, ymin=y_min, ymax=y_max, 
                    color='blue', thickness=_sage_const_2 , gridlines=True, 
                    axes_labels=['$X (4n)$', '$Y (4y)$'],
                    aspect_ratio=_sage_const_0p1 ) 

puntos_integrales = E.integral_points()
plot_puntos = Graphics()
for P in puntos_integrales:
    if x_min <= P[_sage_const_0 ] <= x_max:
        plot_puntos += point(P[:_sage_const_2 ], color='red', size=_sage_const_120 , zorder=_sage_const_3 )
        # Etiquetado en n real
        if P[_sage_const_1 ] > _sage_const_0 :
            n_label = P[_sage_const_0 ]/_sage_const_4 
            plot_puntos += text(f"n={n_label}", (P[_sage_const_0 ], P[_sage_const_1 ]+_sage_const_12 ), 
                                color='black', fontsize=_sage_const_10 , fontweight='bold')

grafico_final = plot_curva + plot_puntos
grafico_final.save("red_autorreferencial_rank2.png", dpi=_sage_const_300 , figsize=[_sage_const_12 , _sage_const_7 ])

print("Visualización renderizada en 'red_autorreferencial_rank2.png'.")

