

# This file was *autogenerated* from the file infinity_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_50000 = Integer(50000); _sage_const_0 = Integer(0); _sage_const_50 = Integer(50); _sage_const_1 = Integer(1)
import csv
from sage.all import *

def analizar_crecimiento_veta(file_path):
    print("=== ANALISIS DE PERSISTENCIA ESTRUCTURAL ===")
    pasos = []
    with open(file_path, 'r') as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader):
            if i % _sage_const_50000  == _sage_const_0 : # Tomamos muestras cada 50k nodos
                pasos.append({'nodos': i, 'D': int(row['D'])})
    
    print(f"{'Nodos acumulados':<18} | {'Valor D':<15} | {'Densidad Local'}")
    print("-" * _sage_const_50 )
    
    for p in pasos[_sage_const_1 :]:
        densidad = p['nodos'] / float(p['D'])
        print(f"{p['nodos']:<18} | {p['D']:<15} | {densidad:.10f}")

analizar_crecimiento_veta('450000_pairs.csv')

