

# This file was *autogenerated* from the file infinity_robustness.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_100000 = Integer(100000); _sage_const_50 = Integer(50); _sage_const_1 = Integer(1)
import csv
import math
from sage.all import *

def test_infinitud_logaritmica(file_path):
    print("=== TEST DE PENDIENTE: ¿DILUCION O EXTINCION? ===")
    puntos = []
    with open(file_path, 'r') as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader):
            if i > _sage_const_0  and i % _sage_const_100000  == _sage_const_0 :
                puntos.append({'log_n': math.log(i), 'log_D': math.log(int(row['D']))})

    print(f"{'Log(Nodos)':<15} | {'Log(D)':<15} | {'Pendiente (Alpha)'}")
    print("-" * _sage_const_50 )
    
    for i in range(len(puntos)-_sage_const_1 ):
        # Calculamos la pendiente entre puntos logarítmicos
        dy = puntos[i+_sage_const_1 ]['log_D'] - puntos[i]['log_D']
        dx = puntos[i+_sage_const_1 ]['log_n'] - puntos[i]['log_n']
        alpha = dy / dx
        print(f"{puntos[i]['log_n']:<15.4f} | {puntos[i]['log_D']:<15.4f} | {alpha:.4f}")

test_infinitud_logaritmica('450000_pairs.csv')

