

# This file was *autogenerated* from the file MW_sum.sage
from sage.all_cmdline import *   # import sage library

_sage_const_60 = Integer(60); _sage_const_4p0 = RealNumber('4.0'); _sage_const_13p0 = RealNumber('13.0'); _sage_const_5p0 = RealNumber('5.0'); _sage_const_19p0 = RealNumber('19.0'); _sage_const_2 = Integer(2); _sage_const_6p0 = RealNumber('6.0'); _sage_const_1 = Integer(1); _sage_const_2p0 = RealNumber('2.0'); _sage_const_8p0 = RealNumber('8.0'); _sage_const_0p0001 = RealNumber('0.0001')
def ejecutar_validacion_manual():
    print("-" * _sage_const_60 )
    print("VALIDACIÓN MANUAL: OPERADOR LUCERO BRAVO vs MORDELL-WEIL")
    print("-" * _sage_const_60 )

    # Datos de tu Preprint (Anclas)
    # Ancla 1: i=4, j=7  -> x=4, y = 2(7)-1 = 13
    # Ancla 2: i=5, j=10 -> x=5, y = 2(10)-1 = 19
    x1, y1 = _sage_const_4p0 , _sage_const_13p0 
    x2, y2 = _sage_const_5p0 , _sage_const_19p0 

    print(f"Punto P1 (Ancla 1): ({x1}, {y1})")
    print(f"Punto P2 (Ancla 2): ({x2}, {y2})")

    try:
        # 1. Calcular la pendiente m entre P1 y P2
        # m = (y2 - y1) / (x2 - x1)
        m = (y2 - y1) / (x2 - x1)
        print(f"\n1. Pendiente calculada (m): {m}")

        # 2. Encontrar x3 (el tercer punto donde la recta corta la curva)
        # La fórmula para y^2 = 4x^3 + Ax^2 + Bx + C es:
        # x1 + x2 + x3 = (m^2 / coeficiente_x3) - (coeficiente_x2 / coeficiente_x3)
        # En tu caso: coeficiente_x3 = 4, coeficiente_x2 = -6
        
        termino1 = (m**_sage_const_2  / _sage_const_4p0 )
        termino2 = (-(-_sage_const_6p0 ) / _sage_const_4p0 ) # - (a2 / a3) -> - (-6 / 4)
        
        x3 = termino1 + ( -_sage_const_6p0  / _sage_const_4p0  ) - x1 - x2
        
        # 3. Encontrar y3 (el reflejo del punto en la curva)
        y3_en_recta = m * (x3 - x1) + y1
        y3 = -y3_en_recta # La suma en curvas elípticas requiere reflejar respecto al eje x

        # 4. Traducir a tu variable j: j = (y + 1) / 2
        i_res = x3
        j_res = (y3 + _sage_const_1 ) / _sage_const_2p0 

        print(f"\n--- RESULTADOS ---")
        print(f"Coordenada i (x3): {i_res}")
        print(f"Valor y resultante: {y3}")
        print(f"Variable j calculada: {j_res}")

        # Verificación con tu Ancla 3: (8, 21)
        if abs(i_res - _sage_const_8p0 ) < _sage_const_0p0001 :
            print("\n¡RESULTADO POSITIVO!")
            print("La ley de grupo clásica coincide con tu Red Autorreferencial.")
        else:
            print("\nANÁLISIS DE DISCREPANCIA:")
            print(f"La suma de Mordell-Weil cae en i={i_res}, no en i=8.")
            print("Esto sugiere que tu red tiene una REGLA DE COMPOSICIÓN PROPIA,")
            print("posiblemente basada en tu operador E_k(x) y no en la secante clásica.")

    except Exception as e:
        print(f"Error en el proceso: {e}")

# ESTA ES LA LÍNEA QUE FALTABA PARA MOSTRAR LOS RESULTADOS
ejecutar_validacion_manual()

