

# This file was *autogenerated* from the file rank_ec.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2)# Definimos la curva m^2 = 4n^3 - 6n^2 + 2n + 1
# Para Sage, usamos la forma y^2 = 4x^3 - 6x^2 + 2x + 1
# Los coeficientes de una curva y^2 + a1*xy + a3*y = x^3 + a2*x^2 + a4*x + a6
# Para la nuestra: a1=0, a3=0, a2=-6/4=-1.5, a4=2/4=0.5, a6=1/4=0.25
# PERO para evitar fracciones que causen error en integral_points, usamos:
E = EllipticCurve([_sage_const_0 , -_sage_const_6 , _sage_const_0 , _sage_const_8 , _sage_const_16 ]) # Este es el modelo integral escalado correcto

print(f"Analizando Curva: {E}")

# Buscamos puntos enteros en este modelo
pts = E.integral_points()

print("\n--- Resultados de Validación ---")
for p in pts:
    x_val, y_val = p[_sage_const_0 ], p[_sage_const_1 ]
    
    # Aquí está la clave del mapeo inverso exacto:
    # Según la derivación de tu operador:
    n = x_val / _sage_const_4 
    m = abs(y_val) / _sage_const_4 
    
    # Verificamos si n es entero y si m permite un j entero
    if n.is_integer() and (_sage_const_1  + m).is_integer() and (_sage_const_1  + m) % _sage_const_2  == _sage_const_0 :
        n_final = int(n)
        j_final = int((_sage_const_1  + m) / _sage_const_2 )
        if n_final > _sage_const_1 :
            print(f"Punto del Operador Detectado: n={n_final}, j={j_final} (OK)")

