

# This file was *autogenerated* from the file test_mapa_racional.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_11 = Integer(11); _sage_const_19 = Integer(19); _sage_const_8 = Integer(8); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_10 = Integer(10); _sage_const_21 = Integer(21); _sage_const_16 = Integer(16); _sage_const_29 = Integer(29); _sage_const_84 = Integer(84); _sage_const_180 = Integer(180); _sage_const_840 = Integer(840); _sage_const_480 = Integer(480); _sage_const_1624 = Integer(1624); _sage_const_12 = Integer(12); _sage_const_24 = Integer(24); _sage_const_40 = Integer(40); _sage_const_60 = Integer(60); _sage_const_50000 = Integer(50000); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_70 = Integer(70); _sage_const_90 = Integer(90)
import pandas as pd
from sage.all import *
import time

# 1. Cargar la base de datos
print("Cargando base de datos...")
try:
    df = pd.read_csv('450000_pairs.csv')
    df['d'] = df['d'].astype(int)
    df['n'] = df['n'].astype(int)
    df['j'] = df['j'].astype(int)
    df['D'] = df['D'].astype(int)
    print(f"Base de datos cargada: {len(df)} pares")
except FileNotFoundError:
    print("Archivo no encontrado. Usando pares de prueba.")
    df = pd.DataFrame({
        'd': [_sage_const_2 , _sage_const_2 , _sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 , _sage_const_11 , _sage_const_19 ],
        'n': [_sage_const_4 , _sage_const_5 , _sage_const_8 , _sage_const_6 , _sage_const_8 , _sage_const_2 , _sage_const_2 , _sage_const_2 ],
        'j': [_sage_const_7 , _sage_const_10 , _sage_const_21 , _sage_const_16 , _sage_const_29 , _sage_const_3 , _sage_const_4 , _sage_const_5 ],
        'D': [_sage_const_84 , _sage_const_180 , _sage_const_840 , _sage_const_480 , _sage_const_1624 , _sage_const_12 , _sage_const_24 , _sage_const_40 ]
    })

# 2. Función mejorada para cálculo riguroso de rangos
def rigorous_rank_smart(E, max_time=_sage_const_60 ):
    """
    Calcula el rango con la mayor rigurosidad posible.
    Devuelve (rank, status, time_used)
    """
    start_time = time.time()
    N = E.conductor()
    
    # Estrategia 1: Para conductores pequeños, proof=True
    if N < _sage_const_50000 :  # Umbral conservador
        try:
            rank_val = E.rank(proof=True)
            elapsed = time.time() - start_time
            return rank_val, 'rigorous (proof=True)', elapsed
        except Exception as e:
            print(f"    Error en proof=True: {e}")
    
    # Estrategia 2: proof=False + verificación analítica bajo BSD
    try:
        rank_heuristic = E.rank(proof=False)
        rank_analytic = E.analytic_rank()
        elapsed = time.time() - start_time
        
        if rank_heuristic == rank_analytic:
            return rank_heuristic, 'heuristic (consistent with BSD)', elapsed
        else:
            return rank_heuristic, f'heuristic (BSD analytic={rank_analytic})', elapsed
            
    except Exception as e:
        elapsed = time.time() - start_time
        return None, f'error: {str(e)}', elapsed

# 3. Función principal COMPLETA
def test_rational_map_complete(d, n, j, D, test_index):
    """
    Test completo del mapa racional con todas las verificaciones.
    """
    print(f"\n{'='*_sage_const_60 }")
    print(f"TEST {test_index}: Par (d={d}, n={n}, j={j})")
    print(f"{'='*_sage_const_60 }")
    
    # VERIFICACIÓN 1: Fórmulas para D
    D_calc1 = n * (n - _sage_const_1 ) * (d * n - d + _sage_const_1 )
    D_calc2 = _sage_const_2  * j * (j - _sage_const_1 )
    
    if D != D_calc1 or D != D_calc2:
        print(f"ERROR: Inconsistencia en D")
        return None
    
    print(f"✓ D verificado: {D}")
    
    # VERIFICACIÓN 2: Construcción de curvas
    C = j * (j - _sage_const_1 ) * (_sage_const_2  * j - _sage_const_1 )
    E_D = EllipticCurve([-D**_sage_const_2 , _sage_const_0 ])
    E_C = EllipticCurve([-C**_sage_const_2 , _sage_const_0 ])
    
    print(f"✓ C calculado: {C}")
    print(f"✓ E_D: y² = x³ - {D}²x")
    print(f"✓ E_C: y² = x³ - {C}²x")
    
    # VERIFICACIÓN 3: Construcción del mapa φ
    lambda_sq = (_sage_const_2 *j - _sage_const_1 ) / _sage_const_2 
    lambda_val = sqrt(lambda_sq)
    
    x, y = var('x y')
    phi_x = lambda_sq * x
    phi_y = lambda_sq * lambda_val * y
    
    print(f"\n--- Mapa racional φ ---")
    print(f"λ² = (2j-1)/2 = {lambda_sq}")
    print(f"φ(x,y) = ({phi_x}, {phi_y})")
    
    # VERIFICACIÓN 4: Prueba algebraica de que φ es morfismo
    print(f"\n--- Verificación algebraica ---")
    lhs = phi_y**_sage_const_2 
    rhs = phi_x**_sage_const_3  - C**_sage_const_2  * phi_x
    diff = (lhs - rhs).subs(y**_sage_const_2  == x**_sage_const_3  - D**_sage_const_2  * x).full_simplify()
    
    if diff == _sage_const_0 :
        print(f"✓ φ es morfismo (diferencia = 0)")
    else:
        print(f"✗ ERROR: diferencia = {diff}")
        return None
    
    # VERIFICACIÓN 5: Puntos de torsión
    print(f"\n--- Puntos de torsión ---")
    torsion_points = E_D.torsion_points()
    for P in torsion_points:
        if P == E_D(_sage_const_0 ):
            print(f"  O → O")
            continue
        
        xP, yP = P.xy()
        xQ = lambda_sq * xP
        yQ = lambda_sq * lambda_val * yP
        
        if yQ**_sage_const_2  == xQ**_sage_const_3  - C**_sage_const_2  * xQ:
            print(f"  {P} → ({xQ}, {yQ}) ✓")
        else:
            print(f"  {P} → ({xQ}, {yQ}) ✗")
    
    # VERIFICACIÓN 6: Rangos (MEJORADA)
    print(f"\n--- Cálculo de rangos ---")
    
    cond_D = E_D.conductor()
    cond_C = E_C.conductor()
    print(f"  Conductor E_D: {cond_D}")
    print(f"  Conductor E_C: {cond_C}")
    
    print(f"  Calculando rango de E_D...")
    rank_D, status_D, time_D = rigorous_rank_smart(E_D)
    print(f"    → {rank_D} ({status_D}) [{time_D:.1f}s]")
    
    print(f"  Calculando rango de E_C...")
    rank_C, status_C, time_C = rigorous_rank_smart(E_C)
    print(f"    → {rank_C} ({status_C}) [{time_C:.1f}s]")
    
    # VERIFICACIÓN 7: Racionalidad de λ
    print(f"\n--- Propiedades de λ ---")
    if lambda_sq in QQ and lambda_sq.is_square():
        print(f"  λ es RACIONAL: {lambda_val}")
    else:
        print(f"  λ es IRRACIONAL")
        print(f"  → φ es isomorfismo sobre ℚ(√({_sage_const_2 *j-_sage_const_1 }))")
    
    # RESUMEN
    print(f"\n--- Resumen ---")
    print(f"• Par: (d={d}, n={n}, j={j})")
    print(f"• Rangos: E_D={rank_D}, E_C={rank_C}")
    
    return {
        'd': d, 'n': n, 'j': j, 'D': D, 'C': C,
        'rank_D': rank_D, 'status_D': status_D,
        'rank_C': rank_C, 'status_C': status_C,
        'lambda_sq': lambda_sq, 'lambda_val': lambda_val,
        'phi': (phi_x, phi_y)
    }

# 4. Pares de prueba (3 del núcleo + 3 aleatorios)
test_pairs = [
    (_sage_const_2 , _sage_const_4 , _sage_const_7 , _sage_const_84 ),    # Núcleo
    (_sage_const_2 , _sage_const_5 , _sage_const_10 , _sage_const_180 ),  # Núcleo
    (_sage_const_2 , _sage_const_8 , _sage_const_21 , _sage_const_840 ),  # Núcleo
    (_sage_const_5 , _sage_const_2 , _sage_const_3 , _sage_const_12 ),    # Simple
    (_sage_const_11 , _sage_const_2 , _sage_const_4 , _sage_const_24 ),   # Mediano
    (_sage_const_19 , _sage_const_2 , _sage_const_5 , _sage_const_40 ),   # Mediano
]

# 5. Ejecutar tests
print("\n" + "="*_sage_const_70 )
print("TESTEO COMPLETO DEL MAPA RACIONAL")
print("="*_sage_const_70 )

results = []
for idx, (d, n, j, D) in enumerate(test_pairs, _sage_const_1 ):
    try:
        result = test_rational_map_complete(d, n, j, D, idx)
        if result:
            results.append(result)
    except Exception as e:
        print(f"\n✗ Error en test {idx}: {e}")

# 6. Resumen final
print("\n" + "="*_sage_const_70 )
print("RESUMEN FINAL")
print("="*_sage_const_70 )

if results:
    print(f"\nTests exitosos: {len(results)}/{len(test_pairs)}")
    
    print("\nTabla de resultados:")
    print("-" * _sage_const_90 )
    print(f"{'Par':<10} {'D':<8} {'C':<10} {'rank(E_D)':<20} {'rank(E_C)':<20} {'λ'}")
    print("-" * _sage_const_90 )
    
    for r in results:
        par = f"({r['d']},{r['n']},{r['j']})"
        lambda_rational = "R" if (r['lambda_sq'] in QQ and r['lambda_sq'].is_square()) else "I"
        print(f"{par:<10} {r['D']:<8} {r['C']:<10} {r['rank_D']:<3} ({r['status_D'][:15]}) {r['rank_C']:<3} ({r['status_C'][:15]}) {lambda_rational}")
    
    # Estadísticas
    print(f"\nEstadísticas de métodos:")
    methods = {}
    for r in results:
        methods[r['status_D']] = methods.get(r['status_D'], _sage_const_0 ) + _sage_const_1 
        methods[r['status_C']] = methods.get(r['status_C'], _sage_const_0 ) + _sage_const_1 
    
    for method, count in methods.items():
        print(f"  {method}: {count}")
else:
    print("No hay resultados.")

