

# This file was *autogenerated* from the file tunnell_validation.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1000 = Integer(1000); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_32 = Integer(32); _sage_const_8 = Integer(8); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_64 = Integer(64); _sage_const_16 = Integer(16); _sage_const_1 = Integer(1); _sage_const_50 = Integer(50)
import csv
import os
from sage.all import ZZ

# --- CONFIGURACIÓN ---
INPUT_FILE = "450000_pairs.csv"
OUTPUT_FILE = "confirmacion_tunnell_final.csv"
SAMPLE_LIMIT = _sage_const_1000   # Cantidad de casos a validar

def is_congruent_tunnell(n):
    """
    Implementación del Test de Tunnell para números congruentes.
    Verifica si n es un número congruente (asumiendo n libre de cuadrados).
    """
    if n % _sage_const_2  != _sage_const_0 : # Caso n impar
        f = lambda x, y, z: _sage_const_2 *x**_sage_const_2  + _sage_const_10 *y**_sage_const_2  + _sage_const_32 *z**_sage_const_2 
        g = lambda x, y, z: _sage_const_2 *x**_sage_const_2  + _sage_const_10 *y**_sage_const_2  + _sage_const_8 *z**_sage_const_2 
        count_f = len([(x,y,z) for x in range(-_sage_const_20 ,_sage_const_21 ) for y in range(-_sage_const_20 ,_sage_const_21 ) for z in range(-_sage_const_20 ,_sage_const_21 ) if f(x,y,z) == n])
        count_g = len([(x,y,z) for x in range(-_sage_const_20 ,_sage_const_21 ) for y in range(-_sage_const_20 ,_sage_const_21 ) for z in range(-_sage_const_20 ,_sage_const_21 ) if g(x,y,z) == n])
        return _sage_const_2  * count_f == count_g
    else: # Caso n par
        n_half = n // _sage_const_2 
        f = lambda x, y, z: _sage_const_8 *x**_sage_const_2  + _sage_const_10 *y**_sage_const_2  + _sage_const_64 *z**_sage_const_2 
        g = lambda x, y, z: _sage_const_8 *x**_sage_const_2  + _sage_const_10 *y**_sage_const_2  + _sage_const_16 *z**_sage_const_2 
        count_f = len([(x,y,z) for x in range(-_sage_const_20 ,_sage_const_21 ) for y in range(-_sage_const_20 ,_sage_const_21 ) for z in range(-_sage_const_20 ,_sage_const_21 ) if f(x,y,z) == n_half])
        count_g = len([(x,y,z) for x in range(-_sage_const_20 ,_sage_const_21 ) for y in range(-_sage_const_20 ,_sage_const_21 ) for z in range(-_sage_const_20 ,_sage_const_21 ) if g(x,y,z) == n_half])
        return _sage_const_2  * count_f == count_g

def get_square_free_part(n):
    """Obtiene la parte libre de cuadrados para el test de Tunnell"""
    return n.squarefree_part()

# --- PROCESAMIENTO ---
if not os.path.exists(INPUT_FILE):
    print(f"Error: No se encuentra {INPUT_FILE}")
else:
    print("Iniciando validación definitiva mediante Teorema de Tunnell...")
    resultados = []
    
    with open(INPUT_FILE, mode='r') as f:
        reader = csv.DictReader(f)
        count = _sage_const_0 
        for row in reader:
            D = ZZ(int(row['D']))
            d_dim = row['d']
            
            # El test de Tunnell se aplica a la parte libre de cuadrados
            D_sf = get_square_free_part(D)
            es_congruente = is_congruent_tunnell(D_sf)
            
            status = "CONFIRMADO (Tunnell)" if es_congruente else "REVISAR"
            
            resultados.append([d_dim, row['n'], row['j'], D, status])
            count += _sage_const_1 
            
            if count % _sage_const_50  == _sage_const_0 :
                print(f"Validando: {count}/{SAMPLE_LIMIT}...")
            if count >= SAMPLE_LIMIT:
                break

    # Escribir el nuevo CSV
    with open(OUTPUT_FILE, mode='w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['d', 'n', 'j', 'D', 'validacion_tunnell'])
        writer.writerows(resultados)

    print(f"\n¡Validación terminada! Archivo generado: {OUTPUT_FILE}")

