

# This file was *autogenerated* from the file twist_extension.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_20 = Integer(20); _sage_const_100 = Integer(100); _sage_const_17 = Integer(17); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_60 = Integer(60)# Versión corregida de twist_extension.sage.py
from sage.all_cmdline import *
from sage.all import *
import csv
import sys

def solve_j(D_val):
    disc = _sage_const_4  + _sage_const_8  * D_val
    if disc > _sage_const_0  and Integer(disc).is_square():
        j_val = (_sage_const_2  + sqrt(disc)) / _sage_const_4 
        if j_val in ZZ: return int(j_val)
    return None

def simulacion_masiva_ants(max_n=_sage_const_20 , max_d=_sage_const_100 , output_csv="verificacion_red_masiva.csv"):
    # Ahora el rango es estrictamente del 1 al 17
    num_rutas = _sage_const_17 
    print(f"\n--- PROTOCOLO MASIVO ANTS: d=2 a {max_d} | n=2 a {max_n} ---")
    print(f"Configuración: {num_rutas} rutas correlativas | Rigor: Rank Bound\n")
    
    headers = ['n', 'd', 'D_nd', 'j_anchor', 'D_j2', 'Ruta', 'N_SF', 'RankB', 'Es_Congruente']
    # Inicializamos stats para las 17 rutas
    stats = {i: {'intentos': _sage_const_0 , 'exitos': _sage_const_0 } for i in range(_sage_const_1 , num_rutas + _sage_const_1 )}
    total_intentos = _sage_const_0 
    total_exitos = _sage_const_0 

    with open(output_csv, 'w', newline='') as f:
        csv.writer(f).writerow(headers)

    try:
        for d in range(_sage_const_2 , max_d + _sage_const_1 ):
            buffer = []
            anclajes_en_d = _sage_const_0 
            exitos_en_d = _sage_const_0 
            
            sys.stdout.write(f"d={d:<3} | ")
            sys.stdout.flush()
            
            for n in range(_sage_const_2 , max_n + _sage_const_1 ):
                D_nd = n * (n - _sage_const_1 ) * (d * n - d + _sage_const_1 )
                j = solve_j(D_nd)
                
                if j is not None:
                    D_j2 = j * (j - _sage_const_1 ) * (_sage_const_2  * j - _sage_const_1 )
                    
                    try:
                        E_anchor = EllipticCurve([_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-(Integer(D_j2).squarefree_part())**_sage_const_2 , _sage_const_0 ])
                        if E_anchor.rank_bound() > _sage_const_0 :
                            anclajes_en_d += _sage_const_1 
                            
                            # Diccionario reindexado del 1 al 17 sin saltos
                            rutas_dict = {
                                _sage_const_1 : D_j2**_sage_const_2  - _sage_const_1 , 
                                _sage_const_2 : _sage_const_2 *D_j2 + _sage_const_1 , 
                                _sage_const_3 : _sage_const_2 *D_j2 - _sage_const_3 , 
                                _sage_const_4 : (D_j2**_sage_const_2  - _sage_const_2 *D_j2 - _sage_const_2 )//_sage_const_2 ,
                                _sage_const_5 : D_j2**_sage_const_2  - _sage_const_2 *D_j2, 
                                _sage_const_6 : D_j2**_sage_const_2  - _sage_const_2 *D_j2 - _sage_const_1 , 
                                _sage_const_7 : D_j2**_sage_const_2  + _sage_const_1 , 
                                _sage_const_8 : _sage_const_2 *D_j2**_sage_const_2  + _sage_const_1 ,
                                _sage_const_9 : _sage_const_2 *D_j2**_sage_const_2  - _sage_const_1 , 
                                _sage_const_10 : D_j2**_sage_const_2  - D_j2, 
                                _sage_const_11 : D_j2 - _sage_const_1 , 
                                _sage_const_12 : D_j2 + _sage_const_1 ,
                                _sage_const_13 : _sage_const_2 *D_j2 - _sage_const_1 , # Antigua 14 (o similar corregida)
                                _sage_const_14 : _sage_const_2 *D_j2 + _sage_const_3 , 
                                _sage_const_15 : _sage_const_2 *D_j2 + _sage_const_2 , 
                                _sage_const_16 : _sage_const_2 *D_j2 - _sage_const_2 , 
                                _sage_const_17 : D_j2**_sage_const_2  - _sage_const_2 *D_j2 - _sage_const_2 
                            }

                            for id_r, val in rutas_dict.items():
                                if val <= _sage_const_1 : continue
                                N = Integer(val).squarefree_part()
                                
                                try:
                                    rb = EllipticCurve([_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-N**_sage_const_2 ,_sage_const_0 ]).rank_bound()
                                    exito = (rb > _sage_const_0 )
                                except:
                                    rb, exito = _sage_const_0 , False

                                stats[id_r]['intentos'] += _sage_const_1 
                                total_intentos += _sage_const_1 
                                if exito:
                                    stats[id_r]['exitos'] += _sage_const_1 
                                    total_exitos += _sage_const_1 
                                    exitos_en_d += _sage_const_1 
                                
                                buffer.append([n, d, D_nd, j, D_j2, id_r, N, rb, str(exito)])
                    except: pass
            
            if buffer:
                with open(output_csv, 'a', newline='') as f:
                    csv.writer(f).writerows(buffer)
                sys.stdout.write(f"Anclajes: {anclajes_en_d:<2} | Éxitos: {exitos_en_d:<4} | OK\n")
            else:
                sys.stdout.write("Skip\n")
            sys.stdout.flush()

    except KeyboardInterrupt:
        print("\n\n[!] INTERRUPCIÓN MANUAL.")

    # Reporte Final
    print("\n" + "="*_sage_const_60 )
    print(f"{'ROUTE':<8} | {'SUCCESSES/TOTAL':<15} | {'RATE %':<10}")
    print("-" * _sage_const_60 )
    for i in range(_sage_const_1 , num_rutas + _sage_const_1 ):
        s = stats[i]
        if s['intentos'] > _sage_const_0 :
            tasa = float(s['exitos'] / s['intentos'] * _sage_const_100 )
            print(f"Route {i:<3} | {s['exitos']:>6}/{s['intentos']:<8} | {tasa:>7.2f}%")
    
    if total_intentos > _sage_const_0 :
        print("-" * _sage_const_60 )
        tasa_g = float(total_exitos / total_intentos * _sage_const_100 )
        print(f"TOTAL    | {total_exitos:>6}/{total_intentos:<8} | {tasa_g:>7.2f}%")
    print("="*_sage_const_60 )

if __name__ == "__main__":
    simulacion_masiva_ants()

